spring:
  application:
    name: auth-service

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  sql:
    init:
      mode: never

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c

  endpoints:
    web:
      exposure:
        include: health, metrics, info

opentelemetry:
  exporter:
    logging:
      enabled: true
  sdk:
    enabled: true

#logging:
#  level:
    #io.opentelemetry.exporter.logging: DEBUG
    #org.springframework.web: DEBUG

# Переходим на Logback с JSON форматом логов
logging:
  level:
    io.opentelemetry.exporter.logging: DEBUG
    org.springframework.web: DEBUG

server:
  port: 8083

app:
  security:
    jwt-secret: c0382cfa-92ca-4c88-8c67-17f5e60dd71c
    public-endpoints: "/users/register,/users/login, /actuator/**"
    jwt-expiration: 3600