spring:
  application:
    name: cart-service
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info

app:
  security:
    jwt-secret: c0382cfa-92ca-4c88-8c67-17f5e60dd71c
    jwt-expiration: 3600
    public-endpoints: "/actuator/health,/actuator/info, /actuator/**"

logging:
  level:
    io.opentelemetry.exporter.logging: DEBUG
    org.springframework.web: DEBUG
